### ISSUE TITLE
the launcher kees crashign when I attempt to move stuff

### ISSUE THREAD

**Issue by marrie** [Deletescape-Media/Lawnchair#1247]
## Description
When moving items around using  the talkback actions the launcher will crash. I did send logs in February or so but so far this has not be fixed
## Expected Behavior
What should happen is this, the launcher should not crash if I let's say move an icon from 1 page to another, or even into a folder.
## Actual Behavior
The app crashes and the close and send feedback that android brings up shows up.
## Steps to Reproduce
1. Make sure launcher  is set to launcheer.
2. Hit home and find an item you want to move
3. Bring up the talk back actions menu
4. Tap move
5. Tap on the new place you want to move the item to.

This is when the crash happens. The items are moved but the app will still crash. It works afterwords but it should not in theory be doing this.

## Environment
Device: moto z2 force
Android version: 8.0

I've forgotten the latest version of the launcher  but it is what is on the app store. I'm not a part  of the beta program so this is a public release.

Thanks.

**Comment by divadsn** [comment]
Is it still present on the latest version?

**Comment by marrie** [comment]
I actually just migrated myself to a new phone so right now cannot test. Can anyone else confirm that the issue is fixed or not

Thanks.

**Comment by chaltain** [comment]
Yes, I just updated LawnChair from the Play Store on my S7 running Android 7, and I still see the LawnChair crash when I move an icon around on a home page. I sent in a report through LawnChair just a few minutes ago.

**Comment by ghost** [comment]
Please note that this crash doesn't occur when an item is moved around on the screen. It only occurs when Talkback is used to move the item. So in order to reproduce the crash, enable Talkback in the accessibility settings first. Then use Talkback's local context menu to move an item by flicking a finger on screen up and then to the right quickly, tapping actions and then tapping move item, followed by the position on screen where you want the item moved. The voice will say "item moved," and then the crash will occur. I just confirmed this here on my Moto E4 running Android 7.1.1, latest stable Lawnchair from Play Store.

**Comment by ghost** [comment]
Sorry, each tap I mentioned should be a double tap with Talkback's default settings. I forget that I use single tap mode here, which is not the default, and has for some years been considered experimental, though it works well for me.
