### ISSUE TITLE
Circular Icons are cropped

### ISSUE THREAD

**Issue by PlugaruT** [Deletescape-Media/Lawnchair#1556]
## Description

Icons are cropped on all the sides.

## Expected Behavior

Icons should not be cropped. 🤷‍♂ 

## Actual Behavior

Just normal use of the launcher, icons are cropped on all 4 sides, screenshot below.
Turning on/off adaptive icons creation doesn't help.

## Steps to Reproduce

![photo_2019-05-14_09-44-21](https://user-images.githubusercontent.com/6437932/57676445-2e114380-762d-11e9-8648-51c5f7d7aa17.jpg)

## Environment

* Device: OnePlus 5
* Android version: 9.0
* Launcher version: 2.0.2066
* Rom: OxygenOS

## Logcat

 

```
your log here
```

**Comment by nyancrimew** [comment]
This is a known issue (actually introduced by Google, yay) and we'll look into fixing it!

**Comment by PlugaruT** [comment]
I think this was fixed in `alpha-2198` version.

**Comment by bernimoses** [comment]
It's not fixed for me.
![Screenshot_20190628-094141](https://user-images.githubusercontent.com/239049/60336037-9169f180-999f-11e9-9fc5-a40b6f49e5dd.png)

**Comment by suphon-t** [comment]
@bernimoses clearing your icon cache should resolve that.

**Comment by bernimoses** [comment]
> @bernimoses clearing your icon cache should resolve that.

How can i do that? Tried clearing app cache, app settings -> Theme -> Reset custom icons, reboot.

**Comment by suphon-t** [comment]
Lawnchair settings > 3 dots menu > developer options > check “Always clear icon cache”

Then exit out of the settings, let the icons reload and then disable the same checkbox.

**Comment by bernimoses** [comment]
Awesome works perfectly. 👍 Thanks
