### ISSUE TITLE
After restoring backup At a glance widget crashes Lawnchair

### ISSUE THREAD

**Issue by fordownloads** [Deletescape-Media/Lawnchair#1629]
![scrrr](https://user-images.githubusercontent.com/49860671/60737836-b1e10f80-9f8e-11e9-8858-c220d8ad35d7.png)

## Description

After cleaning lawnchair data and restoring backup on desktop appears white square with lawnchair logo instead At a glance widget. When i try to move this widget Lawnchair crashes. If I tap widget i'll get message about creating widget but when i click OK nothing happens.
Also Lawnchair crashes when you try to move any unloaded widget after restoring

## Expected Behavior

Restoring backups should also properly restore At a glance widget

## Actual Behavior

Restoring backup did not resetore At a glance widget 

## Steps to Reproduce

1. Create backup with At a glance widget
2. Go to Android Settings and clear data & cache of Lawnchair
3. Restore backup
4. You'll see a square instead of At a glance
5. Try to move/resize/click
6. Lawnchair gets crashed

## Environment

* Device: x00t
* Android version: Pie
* Launcher version: 2268
* Rom: Pixel Experience

## Logcat

 

(after trying to move)
https://del.dog/upolifenuf

**Comment by DanGLES3** [comment]
Yeah,that's due to the fact that since the at a glance widget was turned into a regular widget (that you can drag and resize) in the latest builds a migration script was made but unfortunately that script currently doesn't seem to work with backuos

**Comment by nyancrimew** [comment]
This should have been fixed in alpha 2279

**Comment by tnfssc** [comment]
This issue still persists

https://user-images.githubusercontent.com/29162020/120104600-cf1aba80-c172-11eb-882e-ce0303c8ab1e.mp4

https://del.dog/ehaphyngeg
