### ISSUE TITLE
[BUG] Blurry recent

### ISSUE THREAD

**Issue by SeeTurtlee** [Deletescape-Media/Lawnchair#2762]
### Describe the bug

When I swipe up to my recents, whatever app I was in gets blurred out (only happens when translucent background is on under recents setting)

### Steps to reproduce

1. Turn on translucent backgrounds
2. Swipe into recents
3. View the blurry page

### Expected behavior

A not blurry recent page

### Screenshots

![Screenshot_20220711-155727](https://user-images.githubusercontent.com/109108253/178348695-3c8b4b75-3e0d-410f-ad56-e0ad8555c271.png)

### Device information

- Device: [Google Pixel 6 Pro]
- OS: [stock ROM Android version 12.0]
- App version [12.1.0 alpha 3

**Comment by SuperDragonXD** [comment]
If I remember correctly, it is an issue of the 'Live Tile' feature and should be fixed in the dev builds (see [this commit](https://github.com/LawnchairLauncher/lawnchair/commit/edc5c080f6571cf348f65cfd72b8545ba738f45e)).

You can try disabling `ENABLE_QUICKSTEP_LIVE_TILE` (launch activity `com.android.launcher3.settings.SettingsActivty` on the `Lawnchair` app using Activity Launcher or similar, then find that in 'Feature Flags' then disable) and see if it fixes the issue for you. If it doesn't,  unsure what the issue is. Try downloading the latest debug version and see if it fixes it.

See also #2633

**Comment by SuperDragonXD** [comment]
Fixed in Lawnchair 12.1 Alpha 4. Closing this issue.

**Comment by pacjo** [comment]
This issue is still present, maybe a regression? Turning off "Translucent background" gets rid of the unwanted blur.

Version: Lawnchair 13 Dev (GH actions # 55 (one of the last runs of #3785 ))
OS: crDroid 9.11 (A13), November security patch
Device: Redmi Note 10 Pro global (sweet)

https://github.com/LawnchairLauncher/lawnchair/assets/56438628/a3f900cb-4812-4dff-bfc1-dff7984b9fa3
