### ISSUE TITLE
[BUG] [META] Adding widgets causes Lawnchair to crash

### ISSUE THREAD

**Issue by SuperDragonXD** [Deletescape-Media/Lawnchair#2820]
### Describe the bug

This is a meta issue for all the widget crashing issues *relating to this crash message*: `java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference`. All issues relating to this will be closed and will be linked to this meta issue.

### Steps to reproduce

1. Go to the widgets menu
2. Find a widget, and add it to the home screen
3. See error

### Expected behavior

Lawnchair should not crash, or if there's an internal error, simply discard the attempt to add the widget.

### Screenshots

Note: Crash notification didn't appear since I muted notifications

https://user-images.githubusercontent.com/70206496/183589954-cffc0191-a399-4a83-9e48-0e804e497c9f.mp4

### Device information

- Device: Multiple Devices
- OS: Any OS that supports widgets and Lawnchair
- App version 11+

### Additional context

Here are the things that increases the chance Lawnchair will crash and show this specific error:

* Lawnchair is set as the default launcher
* The widget has a setup screen

**Comment by kytta** [comment]
I don’t know how interested you are in the bug reports, since they all look pretty much the same, but here’s one from me. Same story: tried adding a widget (it has a setup screen), Lawnchair crashed.

https://gist.github.com/kytta/57ea0dcfa229e8fa54ab52fa9c10362c

**What fixed it for me** was setting a different launcher as default, then adding the widget to Lawnchair, then setting it as default again.

**Comment by Golde2341** [comment]
Fixed on lawnchair 12.1 alpha 4

**Comment by SuperDragonXD** [comment]
> Fixed on lawnchair 12.1 alpha 4

No, can still reproduce this type of crash. There are several crashes induced by adding widgets; this is one of them. What you're saying is that a different type of crash from adding widgets has been fixed.

**Comment by Goooler** [comment]
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider'
 on a null object reference in method 'void com.android.launcher3.Launcher.completeAddAppWidget(int, com.android.launcher3.model.data.ItemInfo, 
 android.appwidget.AppWidgetHostView, com.android.launcher3.widget.LauncherAppWidgetProviderInfo)'
    at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
    at com.android.launcher3.Launcher$4.run(Launcher.java:1)
    at com.android.launcher3.Workspace$6.run(Workspace.java:4)
    at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(:2)
    at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
    at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
    at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
    at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
    at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
    at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
    at android.view.Choreographer.doCallbacks(Choreographer.java:866)
    at android.view.Choreographer.doFrame(Choreographer.java:792)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8669)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by ruben2s** [comment]
Same exact error here in Galaxy S9+ (Android 10), latest Lawnchair dev build.

**Comment by vladimirhr98** [comment]
Same problem while trying to add samsung note widget on version 12.1.0 alpha 

Lawnchair bug report Jan 8, 2023 22:18:58
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: samsung
build.device: d2s
build.display: SP1A.210812.016.N975FXXS8HVJ1
build.fingerprint: samsung/d2sxx/d2s:12/SP1A.210812.016/N975FXXS8HVJ1:user/release-keys
build.hardware: exynos9825
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-N975F
build.product: d2sxx
build.type: user
version.codename: REL
version.incremental: N975FXXS8HVJ1
version.release: 12
version.sdk_int: 31
display.density_dpi: 560
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by vladimirhr98** [comment]
> Fixed on lawnchair 12.1 alpha 4

Lawnchair bug report Jan 8, 2023 22:18:58
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: samsung
build.device: d2s
build.display: SP1A.210812.016.N975FXXS8HVJ1
build.fingerprint: samsung/d2sxx/d2s:12/SP1A.210812.016/N975FXXS8HVJ1:user/release-keys
build.hardware: exynos9825
build.id: SP1A.210812.016
build.manufacturer: samsung
build.model: SM-N975F
build.product: d2sxx
build.type: user
version.codename: REL
version.incremental: N975FXXS8HVJ1
version.release: 12
version.sdk_int: 31
display.density_dpi: 560
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:555)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1106)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:792)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by kud** [comment]
Same here.

```
Lawnchair bug report 15 Jan 2023 00:46:37
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: OnePlus
build.device: OnePlus6T
build.display: ONEPLUS A6013_41_211125
build.fingerprint: OnePlus/OnePlus6T/OnePlus6T:11/RKQ1.201217.002/2111252327:user/release-keys
build.hardware: qcom
build.id: RKQ1.201217.002
build.manufacturer: OnePlus
build.model: ONEPLUS A6013
build.product: OnePlus6T
build.type: user
version.codename: REL
version.incremental: 2111252327
version.release: 11
version.sdk_int: 30
display.density_dpi: 420
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.launcher3.CellLayout.cellToRect(int, int, int, int, android.graphics.Rect)' on a null object reference
	at com.android.launcher3.Workspace.estimateItemPosition(Workspace.java:2)
	at com.android.launcher3.Workspace.getFinalPositionForDropAnimation(Workspace.java:3)
	at com.android.launcher3.Workspace.animateWidgetDrop(Workspace.java:2)
	at com.android.launcher3.Launcher.completeTwoStageWidgetDrop(Launcher.java:10)
	at com.android.launcher3.Launcher$3.run(Launcher.java:1)
	at com.android.launcher3.Workspace.removeExtraEmptyScreenDelayed(Workspace.java:9)
	at com.android.launcher3.Workspace.lambda$removeExtraEmptyScreenDelayed$2(Unknown Source:1)
	at com.android.launcher3.Workspace.o(Unknown Source:0)
	at com.android.launcher3.l3.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by OP-MapleSpace** [comment]
I also have the same error

```
Lawnchair bug report Jan 30, 2023 14:06:34
version: 12.1.0 Alpha 4 (12010005)
commit: b7ad08c
build.brand: samsung
build.device: r8q
build.display: TP1A.220624.014.G781WVLS7GWA1
build.fingerprint: samsung/r8qcsx/r8q:13/TP1A.220624.014/G781WVLS7GWA1:user/release-keys
build.hardware: qcom
build.id: TP1A.220624.014
build.manufacturer: samsung
build.model: SM-G781W
build.product: r8qcsx
build.type: user
version.codename: REL
version.incremental: G781WVLS7GWA1
version.release: 13
version.sdk_int: 33
display.density_dpi: 450
isRecentsEnabled: false

error: Uncaught exception

java.lang.NullPointerException: Attempt to read from field 'android.content.ComponentName android.appwidget.AppWidgetProviderInfo.provider' on a null object reference in method 'void com.android.launcher3.Launcher.completeAddAppWidget(int, com.android.launcher3.model.data.ItemInfo, android.appwidget.AppWidgetHostView, com.android.launcher3.widget.LauncherAppWidgetProviderInfo)'
	at com.android.launcher3.Launcher.completeAddAppWidget(Launcher.java:3)
	at com.android.launcher3.Launcher$4.run(Launcher.java:1)
	at com.android.launcher3.Workspace$6.run(Workspace.java:4)
	at com.android.launcher3.anim.AnimatorListeners$1.onAnimationEnd(Unknown Source:2)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1301)
	at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1086)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

**Comment by adamk33n3r** [comment]
Why isn't this fixed yet?

**Comment by 88572** [comment]
I'm not having this problem.
https://github.com/LawnchairLauncher/lawnchair/assets/82726593/d2d22cb9-3b58-4254-84e7-55c8a350abfb

**Comment by OP-MapleSpace** [comment]
@everypizza1 the bug occurs when you select something with a customizable dialog. OpenWeather's widget is a good example of this.

**Comment by cyberastr4l** [comment]
The fix is on their FAQ. You need to set the phone launcher as default, open lawnchair through it and add the widget, after that make lawnchair the default again. That way it won't crash when your adding the widgets with setup pages. A simple search on Google and found it.

**Comment by ais** [comment]
> The fix is on their FAQ. You need to set the phone launcher as default, open lawnchair through it and add the widget, after that make lawnchair the default again. That way it won't crash when your adding the widgets with setup pages. A simple search on Google and found it.

That's a workaround, not a fix.

ETA: <https://lawnchair.app/faq/>

> […] **here's a temporary solution**:
> 
> 1.  Change the default launcher to your system launcher.
> 2.  Open Lawnchair.
> 3.  Add the widget.
> 4.  Re-set Lawnchair as the default launcher.
> 
> Unfortunately, **there isn't a fix for this yet**.

**Comment by anyback** [comment]
Crash while having another launcher as default for home;

Lawnchair (Debug) bug report Feb 16, 2025 04:49:04
version: 15.Dev.(#1774) (15000000)
commit: 9607dcb
build.brand: motorola
build.device: bangkk
build.display: U1TCS34.22-64-19-4-2
build.fingerprint: motorola/bangkk_ge/bangkk:14/U1TCS34.22-64-19-4-2/305d4a-9c98b:user/release-keys
build.hardware: qcom
build.id: U1TCS34.22-64-19-4-2
build.manufacturer: motorola
build.model: moto g84 5G
build.security.level: 2024-12-01
build.product: bangkk_ge
build.type: user
version.codename: REL
version.incremental: 305d4a-9c98b
version.release: 14
version.sdk_int: 34
display.density_dpi: 400
isRecentsEnabled: false

error: Uncaught exception

java.lang.IllegalArgumentException: Bad widget id 42
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.createAppWidgetConfigIntentSender(IAppWidgetService.java:848)
	at android.appwidget.AppWidgetHost.startAppWidgetConfigureActivityForResult(AppWidgetHost.java:320)
	at com.android.launcher3.widget.LauncherWidgetHolder.startConfigActivity(LauncherWidgetHolder.java:235)
	at com.android.launcher3.AppWidgetResizeFrame.lambda$setupForWidget$3(AppWidgetResizeFrame.java:325)
	at com.android.launcher3.AppWidgetResizeFrame.$r8$lambda$XfAwILfqEwKawq7oyWCzz9aqDeA(Unknown Source:0)
	at com.android.launcher3.AppWidgetResizeFrame$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7684)
	at android.view.View.performClickInternal(View.java:7661)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30344)
	at android.os.Handler.handleCallback(Handler.java:1000)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8407)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl.createAppWidgetConfigIntentSender(AppWidgetServiceImpl.java:1017)
	at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(IAppWidgetService.java:410)
	at android.os.Binder.execTransactInternal(Binder.java:1380)
	at android.os.Binder.execTransact(Binder.java:1310)

**Comment by TheNeutrinoRaged** [comment]
> I don’t know how interested you are in the bug reports, since they all look pretty much the same, but here’s one from me. Same story: tried adding a widget (it has a setup screen), Lawnchair crashed.
> 
> https://gist.github.com/kytta/57ea0dcfa229e8fa54ab52fa9c10362c
> 
> **What fixed it for me** was setting a different launcher as default, then adding the widget to Lawnchair, then setting it as default again.

I couldn't add any widgets, they would just disappear and configuration (play store version) and this sorted it for me (pixel 8a a15 march update), thanks!
