### ISSUE TITLE
[FEATURE] Force widgets to be resized.

### ISSUE THREAD

**Issue by fnldstntn** [Deletescape-Media/Lawnchair#2822]
### Describe the feature

Force widgets to be resized as we want. For example, Firefox search widget is 6x2, i want to resize it to 4x1 but doesn't allow me to resize it vertically.  

### Why would it be useful to add?

Better placement on the home screen. 

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20220809-121454_Lawnchair](https://user-images.githubusercontent.com/18335837/183613339-269b49eb-c41f-4ade-940e-55a2a88a8309.png)

**Comment by Nimzux** [comment]
Guys please add this 🙏 ❤️

**Comment by yasanglass** [comment]
Fixed on https://github.com/LawnchairLauncher/lawnchair/commit/59ca9d6d3bc152949a74a6c5e501c3fe9151d194

It will be included in the next release.

**Comment by Amorphous404** [comment]
> Fixed on https://github.com/LawnchairLauncher/lawnchair/commit/59ca9d6d3bc152949a74a6c5e501c3fe9151d194
> 
> It will be included in the next release.

Thank You , have been asking about it in tg support group, no one was able to answer 😅, wait for the next dev build 😇

**Comment by Amorphous404** [comment]
> Fixed on https://github.com/LawnchairLauncher/lawnchair/commit/59ca9d6d3bc152949a74a6c5e501c3fe9151d194
> 
> It will be included in the next release.


I tired out the latest Dev build #1040, still can't resize the widgets freely

Lawnchair Dev Build 12.1.0 1040
![Screenshot_2022-08-19-15-24-23-43_67d7f8591eff9881972c1169b8bca2d8.jpg](https://user-images.githubusercontent.com/96917972/185594973-3c9737d0-e47a-41d0-a79e-674299990327.jpg)

Nova Launcher
![Screenshot_2022-08-19-15-25-02-46_3822ac0e29cfec8970059bb21d01f05e.jpg](https://user-images.githubusercontent.com/96917972/185595012-a7b7d7c3-9270-4b9c-90c0-f98ff38f648a.jpg)

**Comment by yasanglass** [comment]
Hmmm, I guess it can still be improved. It works fine on the widgets I have. As far as I know, that's a Pixel widget and I don't have one so I cant test that one but can you tell me another widget that I can test this issue on?

**Comment by fnldstntn** [comment]
> Hmmm, I guess it can still be improved. It works fine on the widgets I have. As far as I know, that's a Pixel widget and I don't have one so I cant test that one but can you tell me another widget that I can test this issue on?

Hi. İ tried it on Brave browser and Firefox search widgets, it show the resizing but it doesn't resize the widget.

**Comment by dhirenvasnani** [comment]
> Hmmm, I guess it can still be improved. It works fine on the widgets I have. As far as I know, that's a Pixel widget and I don't have one so I cant test that one but can you tell me another widget that I can test this issue on?

I also tried to resize chrome's widget, it isn't working i guess

**Comment by yasanglass** [comment]
Thanks, ill investigate the issue.

**Comment by Amorphous404** [comment]
> Hmmm, I guess it can still be improved. It works fine on the widgets I have. As far as I know, that's a Pixel widget and I don't have one so I cant test that one but can you tell me another widget that I can test this issue on?

The first (music widget) is from:
https://github.com/KieronQuinn/AmbientMusicMod

The second widget is from Google Digital Wellbeing, you can install it from apkmirror, if it didn't come pre-installed.

For Reference You Can Check Out The Nova Launcher Widget Resize, It Pulls it Of Perfectly.


Thank You

**Comment by Amorphous404** [comment]
@yasandev i see the new dev update added 20x20 Grid Size as experimental feature, still it doesn't help to force the widget to resize and the size adhere to Lawnchair grid size

I tested on v2, the widgets are independent of Homescreen grid size and can be resized just as the way we wanted

Maybe The Lawnchair 12 uses the new Api, That's what blocking the widgets to force resize?

"Android 12 introduced a way for widget providers to limit how much the user can resize it"

**Comment by yasanglass** [comment]
The new experimental feature is completely unrelated to this issue even though it can potentially affect this issue.

The force widgets patch I did was just a commit from [Trebuchet](https://github.com/LineageOS/android_packages_apps_Trebuchet). I have plans to work on a fix for the reported bugs of the feature, don't worry.

**Comment by mirsella** [comment]
hello, is this feature still in the latest 12.1.0 alpha 4 ? I can't manage to force resize a widget, but it might be a specific case with this one ? thanks and sorry for bumping this old issue

**Comment by MegaAppster** [comment]
> hello, is this feature still in the latest 12.1.0 alpha 4 ? I can't manage to force resize a widget, but it might be a specific case with this one ? thanks and sorry for bumping this old issue

There's weird behavior with some widgets not being able to be resized if they're already placed on the home screen (ie resizing only directly after placing the widget), not to mention the resizing border on the widget can be heard to see depending on your color scheme
