### ISSUE TITLE
[BUG] Bugs of icons and navigation on tablets

### ISSUE THREAD

**Issue by Markellas** [Deletescape-Media/Lawnchair#2925]
## About the bug

Hello. Installed the latest Alpha version of the Lawnchair 12.1 on my Android 10 tablet and encountered several bugs.

First, when I set the size of the icons to more than 100%, there is a bug and they go over the edge of the screen.

Second, the navigation in the system (3 buttons) are shown on the main screen, which prevents you from working with the Lawnchair.

![Screenshot_2022-09-10-09-19-56-735](https://user-images.githubusercontent.com/105635627/189472077-66831e8a-d8e3-4e36-b4a8-421c26104207.jpeg)

![Screenshot_2022-09-10-09-28-36-603](https://user-images.githubusercontent.com/105635627/189472137-6b5590f8-8dff-44ca-bcd1-6ad8d434a5ee.jpeg)

### My guess of the reason

I think the problem is that these 3 buttons for navigation are displayed on the home screen, which causes the icons and navigation buttons to conflict and this happens

### Steps to reproduce

1. Download and install Lawnchair 12.1 Alpha 4 on any tablet
2. You will see that system navigation shows on the main screen
3. Set size of the icons to more than 100% and see that they go over the edge of the screen

### Expected behavior

I expected that the navigation buttons would not appear on the home screen, and icons would not be hidden under them accordingly

### Screenshots

![Screenshot_2022-09-10-09-28-36-603](https://user-images.githubusercontent.com/105635627/189472233-02304609-4f33-4ffc-9513-c950210ac1e6.jpeg)
![Screenshot_2022-09-10-09-19-56-735](https://user-images.githubusercontent.com/105635627/189472270-fddd7b66-a8e9-4648-95c6-781009af09fb.jpeg)

### Device information

- Device: Lenovo Tab M10 FHD Plus
- OS: stock Android 10
- App version: 12.1.0 Alpha 4

**Comment by Markellas** [comment]
So, nothing has changed

**Comment by Markellas** [comment]
Still the same

**Comment by AngelofVerdant** [comment]
Daaang just seeing this now , is it still happening now ?

**Comment by Markellas** [comment]
Yeah, still the same

**Comment by Moderpach** [comment]
> Yeah, still the same

I would like you to verify that this issue is fixed in this build.

I fix this issue in devices with taskbar. I'm not sure it is also ok for other devices.

https://moderpach-my.sharepoint.com/:u:/g/personal/moderpach_moderpach_onmicrosoft_com/ERotQHMblCpEs3mosWO3FGkBlXgUHXRccZZZSv--bJylQw?e=QhicYz
![Screenshot_20230406-222849](https://user-images.githubusercontent.com/34941512/230408520-a2ac3ef6-5c43-4975-9eef-59dead4c0b73.png)

**Comment by Markellas** [comment]
> > Yeah, still the same
> 
> I would like you to verify that this issue is fixed in this build.
> 
> I fix this issue in devices with taskbar. I'm not sure it is also ok for other devices.
> 
> https://moderpach-my.sharepoint.com/:u:/g/personal/moderpach_moderpach_onmicrosoft_com/ERotQHMblCpEs3mosWO3FGkBlXgUHXRccZZZSv--bJylQw?e=QhicYz ![Screenshot_20230406-222849](https://user-images.githubusercontent.com/34941512/230408520-a2ac3ef6-5c43-4975-9eef-59dead4c0b73.png)

Still doesn't work for me. Also, gestures doesn't work too

![image](https://user-images.githubusercontent.com/105635627/230420097-ea0f9168-0a87-49e1-9fb1-2dc0440f1fcb.png)

**Comment by alabotski** [comment]
Hi
I have similar problem
https://github.com/LawnchairLauncher/lawnchair/issues/3663
