### ISSUE TITLE
[BUG] folder bg does not expand to accomodate all the icons; beyond four apps the icons (of the other apps) become invisible; #2784 behaviour 

### ISSUE THREAD

**Issue by formula-spectre** [Deletescape-Media/Lawnchair#3724]
### Describe the bug

- the folder background remains the tiny square that is on the homescreen/dock
- maximum four app icons are displayed, the other apps are present in the folder, but are invisible 
also related to #2784 dragging icons directly from the app drawer to the folder on the dock creates a shortcut that is twin-linked to the app in the drawer

### Steps to reproduce

- create a folder on the dock
- drag more than four apps inside it
- ???
- no profit

### Expected behavior

the folder background should expand, and all the app icons should be visible, and the shortcut should not be made

### Screenshots

I can't exactly post a screenshot, but I have a video!

https://github.com/LawnchairLauncher/lawnchair/assets/61557475/745ef5f1-9e50-40da-b97f-2ab5ef73ba67

### Device information

- Device: google pixel 6a
- OS:GrapheneOS, android 14
- App version: [e.g. 12.1.0 Alpha 4]

### Additional context

I would love to help fixing the bug, but I'm pretty rusty in android app development, be that in kotlin or java, so sorry :(

**Comment by formula-spectre** [comment]
why is this outdated?

**Comment by MrSluffy** [comment]
> why is this outdated?

12.1-dev is no longer active, and have you faced this 13-dev?

**Comment by formula-spectre** [comment]
yes, i'm experiencing the same thing in 13 dev; i pulled the apk straight from the latest github action (build number 2372)

**Comment by MrSluffy** [comment]
> yes, i'm experiencing the same thing in 13 dev; i pulled the apk straight from the latest github action (build number 2372)

That's odd, when I tried it in emulator works fine. Is it possible you can share latest screen record, that will be great.

**Comment by formula-spectre** [comment]
https://imgur.com/gallery/8sVOFMN  
sorry if I uploaded it on imgur, but it's more than 10MBs.. anyway as you can see the bug persists;
ROM: Graphene OS, android 14

**Comment by MrSluffy** [comment]
does still occur in `14-dev` build ?

**Comment by MrSluffy** [comment]
Fixed by enabling system animation

**Comment by formula-spectre** [comment]
apologies for the late response, I kinda forgot :skull: does it work with system animations disabled?

**Comment by formula-spectre** [comment]
I just tried with the latest release from f-droid, I have system animations disabled and the bug persists; any solution?

**Comment by script26** [comment]
Lawnchair 14 Debug Builds dont have this issue anymore, turned off all animations in dev options

**Comment by formula-spectre** [comment]
> Lawnchair 14 Debug Builds dont have this issue anymore, turned off all animations in dev options

do I get this form the CI/CD apk artefact?

**Comment by script26** [comment]
Oh I just tried it from apkmirror :p

https://www.apkmirror.com/apk/lawnchair/lawnchair-debug/

**Comment by formula-spectre** [comment]
ah I see. well I downloaded the debug build from the CI/CD, and it seems to work fine, so I'm gonna use it and see how stable it is

**Comment by formula-spectre** [comment]
I tried with the latest artifact from CI/CD, and indeed the folders now work properly, but problem: whenever I try to add something to a folder I get a phantom icon on a random position of the screen. is this a known bug? I think I mentioned in an issue before

**Comment by script26** [comment]
I got that installing first time too, for me I just force stopped it in settings in Settings > Apps > Lawnchair > Force stop

The phantom apps disappear afterwards

**Comment by formula-spectre** [comment]
not for me :/
