### ISSUE TITLE
[BUG] [Lawnchair 13] Crash when Opening On Android 11

### ISSUE THREAD

**Issue by chathushkaimasara** [Deletescape-Media/Lawnchair#3787]
### Describe the bug

Lawnchair 13 doesn't work on Android 11

### Steps to reproduce

1. Installed the Lawnchair
2. Clicked open
3. My wallpaper appeared and crashed
![Screenshot_20231128-115627_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/143923312/51ade776-e8ee-416d-8d8c-3c5cbe082120)
4. Opened it again
5. A Black Screen Appeared And Crashed Again
![Screenshot_20231128-114253_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/143923312/89f51d4e-15e8-4d46-a9be-32425f955e1f)

### Expected behavior

Opened The Launcher and run normally
 (I didn't Rooted My Phone)

### Screenshots

![Screenshot_20231128-113849_One UI Home](https://github.com/LawnchairLauncher/lawnchair/assets/143923312/4f3147fb-62a8-4a03-a330-d763e8acfe52)

### Device information

- Device: [Samsung Galaxy M02]
- OS: [One UI Core 3.1, Android 11]
- App version: [Lawnchair 13 Dev #2394]

### Additional context

Lawnchair (Debug) bug report Nov 28, 2023 11:56:26
version: 13 Dev (https://github.com/LawnchairLauncher/lawnchair/issues/2394) (13)
commit: https://github.com/LawnchairLauncher/lawnchair/commit/91028484fda6e83412c3afa777ebf40e5b548522
build.brand: samsung
build.device: a02
build.display: RP1A.200720.012.M022GXXS4BWI2
build.fingerprint: samsung/a02ins/a02:11/RP1A.200720.012/M022GXXS4BWI2:user/release-keys
build.hardware: mt6739
build.id: RP1A.200720.012
build.manufacturer: samsung
build.model: SM-M022G
build.security.level: 2023-09-01
build.product: a02ins
build.type: user
version.codename: REL
version.incremental: M022GXXS4BWI2
version.release: 11
version.sdk_int: 30
display.density_dpi: 300
isRecentsEnabled: false

error: Uncaught exception

android.view.InflateException: Binary XML file line https://github.com/LawnchairLauncher/lawnchair/issues/27 in app.lawnchair.debug:layout/task_desktop: Resource ID #0x106002f
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x106002f
at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:255)
at android.content.res.Resources.getColor(Resources.java:1169)
at com.android.quickstep.views.DesktopTaskView.onFinishInflate(DesktopTaskView.java:124)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:1134)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
at com.android.launcher3.util.ViewPool.inflateNewView(ViewPool.java:106)
at com.android.launcher3.util.ViewPool.lambda$initPool$1(ViewPool.java:69)
at com.android.launcher3.util.ViewPool.$r8$lambda$wSRnQcMZiOmM7xwf4gm88rNehhg(Unknown Source:0)
at com.android.launcher3.util.ViewPool$$ExternalSyntheticLambda1.run(Unknown Source:8)
at java.lang.Thread.run(Thread.java:923)

**Comment by MrSluffy** [comment]
Hi I pushed a [patched](https://github.com/LawnchairLauncher/lawnchair/actions/runs/7045009873) Kindly confirm if it works, Thanks

**Comment by chathushkaimasara** [comment]
> Hi I pushed a [patched](https://github.com/LawnchairLauncher/lawnchair/actions/runs/7045009873) Kindly confirm if it works, Thanks

Hello, Thank you for Trying Fixing it 
But It still Crashing when I opening it

**Comment by MrSluffy** [comment]
Can you send the new logs? The logs should change

**Comment by MrSluffy** [comment]
Make sure you downloaded this, since this the only one have patched
![image](https://github.com/LawnchairLauncher/lawnchair/assets/36076410/384727a3-adc8-445b-800d-3d5e91147657)

**Comment by MrSluffy** [comment]
What's causing the crash : [https://i.imgur.com/TUBiLxi.png](https://i.imgur.com/TUBiLxi.png) the patched since you're using android 11 instead of modifying the legacy layout we created and added one in layout-v30 without `launcher:borderColor="?attr/colorAccentPrimary"` the one that causing crash in your end and since you're experiencing this crash in android 11 [https://i.imgur.com/S00OZtL.png](https://i.imgur.com/S00OZtL.png)

**Comment by DragonFire002** [comment]
> What's causing the crash : https://i.imgur.com/TUBiLxi.png the patched since you're using android 11 instead of modifying the legacy layout we created and added one in layout-v30 without `launcher:borderColor="?attr/colorAccentPrimary"` the one that causing crash in your end and since you're experiencing this crash in android 11 https://i.imgur.com/S00OZtL.png

Your Latest One UI Fix build Fixed the crash and it's All Working On Android 11 on One UI. Except the stretch Animation on App drawer. But the other things are working fine. Thank you

**Comment by chathushkaimasara** [comment]
> Make sure you downloaded this, since this the only one have patched ![image](https://private-user-images.githubusercontent.com/36076410/287031289-384727a3-adc8-445b-800d-3d5e91147657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NjE1ODcsIm5iZiI6MTcwMTQ2MTI4NywicGF0aCI6Ii8zNjA3NjQxMC8yODcwMzEyODktMzg0NzI3YTMtYWRjOC00NDViLTgwMGQtM2Q1ZTkxMTQ3NjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDIwMDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMzg1MmU3YzhhNWUyODYzZTVhNDhhM2Q5NTg1Y2NiNzFhNjNjNjhmMzk1ODI5NWY0NGJkYTBhMDg2MjEzMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kq-lfNtm63WzXNQTQPFQ2Bo48b3Zl6t08Pj3vSjhN5U)

Your Latest One UI Fix build Fixed the crash and it's All Working On Android 11 on One UI. But i have noticed that the stretch Animation on App drawer doesn't work. But the other things are working fine. Thank you

**Comment by MrSluffy** [comment]
> > Make sure you downloaded this, since this the only one have patched ![image](https://private-user-images.githubusercontent.com/36076410/287031289-384727a3-adc8-445b-800d-3d5e91147657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NjE1ODcsIm5iZiI6MTcwMTQ2MTI4NywicGF0aCI6Ii8zNjA3NjQxMC8yODcwMzEyODktMzg0NzI3YTMtYWRjOC00NDViLTgwMGQtM2Q1ZTkxMTQ3NjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDIwMDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMzg1MmU3YzhhNWUyODYzZTVhNDhhM2Q5NTg1Y2NiNzFhNjNjNjhmMzk1ODI5NWY0NGJkYTBhMDg2MjEzMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kq-lfNtm63WzXNQTQPFQ2Bo48b3Zl6t08Pj3vSjhN5U)
> 
> Your Latest One UI Fix build Fixed the crash and it's All Working On Android 11 on One UI. But i have noticed that the stretch Animation on App drawer doesn't work. But the other things are working fine. Thank you

Got it, will investigate it, can you open new issue about it Thanks
