### ISSUE TITLE
[BUG] Crashes on boot if recents provider is enabled by QuickSwitch

### ISSUE THREAD

**Issue by jingyu9575** [Deletescape-Media/Lawnchair#4661]
### Describe the bug

The app crashes on boot, until several seconds later, if the recents provider is enabled by QuickSwitch.

### Steps to reproduce

1. Enable the recents provider in QuickSwitch.
2. Reboot
3. See crash dialog

### Expected behavior

It should not crash.

### Screenshots

![dcf4b26d5df5e197970540f5e279927](https://github.com/user-attachments/assets/52c0d4b7-27b5-45c2-a56c-3324a45b446c)

### Device information

- Device: Xiaomi 12
- OS: LineageOS 21 Android version 14
- App version: 14.Dev.(# 1225)

### Additional context

Maybe this is the problem:

08-17 17:34:35.940  4100  4100 E AndroidRuntime: FATAL EXCEPTION: main
08-17 17:34:35.940  4100  4100 E AndroidRuntime: Process: app.lawnchair.debug, PID: 4100
08-17 17:34:35.940  4100  4100 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.android.quickstep.TouchInteractionService: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4925)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:232)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:317)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8592)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
08-17 17:34:35.940  4100  4100 E AndroidRuntime: Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:605)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:588)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:223)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.LauncherPrefs.getEncryptedPrefs(LauncherPrefs.kt:51)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.LauncherPrefs.chooseSharedPreferences(LauncherPrefs.kt:65)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.LauncherPrefs.getInner(LauncherPrefs.kt:81)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.LauncherPrefs.get(LauncherPrefs.kt:72)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.util.DisplayController$Info.<init>(DisplayController.java:404)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.util.DisplayController.<init>(DisplayController.java:136)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.util.DisplayController$$ExternalSyntheticLambda2.get(D8$$SyntheticClass:0)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$jeoH4EKO3m1c-S7-sJSjrbw_Ei4(Unknown Source:0)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda1.get(D8$$SyntheticClass:0)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:100)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:59)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:134)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at com.android.quickstep.TouchInteractionService.onCreate(TouchInteractionService.java:497)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4912)
08-17 17:34:35.940  4100  4100 E AndroidRuntime:        ... 9 more

**Comment by MrSluffy** [comment]
Please use latest this should be fixed by this 752af659b6689fc4566222c25b0303abab6f989b

**Comment by MrSluffy** [comment]
Please use latest this should be fixed by this : 60e6d505056b086762798a1cd13140b13701be31

**Comment by jingyu9575** [comment]
Hi, I still get this error on new versions. I think it is not in the `resetHomeBounceSeenOnQuickstepEnabledFirstTime` function but `TouchInteractionService.onCreate`, right?

**Comment by CrazyManLabs** [comment]
@MrSluffy 
Hello.
Sorry to bother, but I'm tagging you, as you've implemented fix for this issue initially.

I can confirm, that issue @jingyu9575 mentioned in initial report still persists even in latest nightly, so issue is clearly not fixed and it is preventing users from using Lawnchair as default launcher and task switcher app _(because after each reboot user is forced to somehow restart Lawnchair to make it work again, which is annoing at least and sometimes not even possible without access to PC)_.

Steps to reproduce:
- install Lawnchair 14 _(even latest version will do)_
- install QuickSwitch Magisk module
- open QuickSwitch and set Lawnchair as recents provider
- reboot device, observe Lawnchair crashing on startup _(we do not even need to set it as default launcher app)_

<details>
<summary>Observed error/stack trace</summary>

```
java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked
stacktrace: java.lang.RuntimeException: Unable to create service com.android.quickstep.TouchInteractionService: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4925)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:605)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:588)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:223)
	at com.android.launcher3.LauncherPrefs.getEncryptedPrefs(LauncherPrefs.kt:51)
	at com.android.launcher3.LauncherPrefs.chooseSharedPreferences(LauncherPrefs.kt:65)
	at com.android.launcher3.LauncherPrefs.getInner(LauncherPrefs.kt:81)
	at com.android.launcher3.LauncherPrefs.get(LauncherPrefs.kt:72)
	at com.android.launcher3.util.DisplayController$Info.<init>(DisplayController.java:404)
	at com.android.launcher3.util.DisplayController.<init>(DisplayController.java:136)
	at com.android.launcher3.util.DisplayController$$ExternalSyntheticLambda2.get(D8$$SyntheticClass:0)
	at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0(MainThreadInitializedObject.java:60)
	at com.android.launcher3.util.MainThreadInitializedObject.$r8$lambda$jeoH4EKO3m1c-S7-sJSjrbw_Ei4(Unknown Source:0)
	at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda1.get(D8$$SyntheticClass:0)
	at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:100)
	at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:59)
	at com.android.quickstep.RecentsAnimationDeviceState.<init>(RecentsAnimationDeviceState.java:134)
	at com.android.quickstep.TouchInteractionService.onCreate(TouchInteractionService.java:497)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4912)
	... 9 more
```
</details>

Details:
- Device: OnePlus 8T
- OS: Android 14, Evolution X 9.4 _(Lineage OS 21-based)_
- Lawnchair: [14 Beta 3](https://github.com/LawnchairLauncher/lawnchair/releases/tag/v14.0.0-beta3)
- QuickSwitch: [4.0.3](https://github.com/skittles9823/QuickSwitch/releases/tag/4.0.3)
- Magisk: [Canary 27008](https://github.com/topjohnwu/Magisk/releases/tag/canary-27008)

_P.S.: I would like to help and provide a patch or MR with fix, but issue seems to be complex enough without looking too deep into the code and knowing Android direct boot mode specifics (and I'm not an Android developer :( )._
