### ISSUE TITLE
Icon style resets when uninstalling an app

### ISSUE THREAD

**Issue by AlessandroGalvan** [Deletescape-Media/Lawnchair#4961]
### Describe the bug

when uninstalling an app the themed icons setting is set to off

### Steps to reproduce

set themed icons on, uninstall an app.

### Expected behavior

it should not go off

### Device information

- Device: [e.g. Samsung s21+]
- OS: [e.g. stock ROM Android version 14.0]
- App version: [e.g. 14 beta 3]

**Comment by MrSluffy** [comment]
fixed latest nightly

**Comment by TheRedCyclops** [comment]
This is still happening for the work profile on the latest nightly

**Comment by TheRedCyclops** [comment]
I will open a new issue
