### ISSUE TITLE
[BUG] crashes when set as recents provider

### ISSUE THREAD

**Issue by 0xAbdiiii** [Deletescape-Media/Lawnchair#5047]
### Describe the bug

crashes at startup when set as the recents provider.

### Steps to reproduce

1. set it as the recents provider
2. device restarts
3. lawnchair debug can't open (crashes instantly)

### Expected behavior

doesn't crash.

### Device information

- Device: Redmi A1+
- OS: Stock rom Android 12 (GO Edition)
- App version: 15-dev (a35d1f2a68896d325d42a0d815b65aec0e582887)

### Additional context

first crash log at device restart

[Lawnchair (Debug) bug report Dec 5, 2024 12_14_56 PM.txt](https://github.com/user-attachments/files/18019151/Lawnchair.Debug.bug.report.Dec.5.2024.12_14_56.PM.txt)

second crash log if you try to open the app again

![Lawnchair (Debug) bug report Dec 6, 2024 3_17_08 PM.txt](https://github.com/user-attachments/files/18036720/Lawnchair.Debug.bug.report.Dec.6.2024.3_17_08.PM.txt)

**Comment by s0m3th1ng-r4nd0m** [comment]
this is the first L15 nightly that is usable for my device.

**Comment by guniens** [comment]
Kind of related I think:

I can set Lawnchair (latest nightly obv) as recents provider, device reboot and Lawnchair works but it's not working as a recents provider at all, when launching an app:
- App icon disappears for a moment
- No launch animation
- Swipe Up to go home not working
- Swipe Back to close app also no animation, freeze for a second and goes back to Lawnchair
- Lawnchair's recents settings also not working

This on a Pixel 8, Android 15 (latest updates) and latest Lawnchair nightly build.

EDIT: Just noticed that apps' icons become bigger then the others after launching, a reboot of Lawnchair fixes it but the problem happens again as soon as you launch an app, icon pack is: You Icons.

**Comment by s0m3th1ng-r4nd0m** [comment]
![Screenshot_20241205-141206.png](https://github.com/user-attachments/assets/5106b769-72de-40bd-a58c-d6474b2df2f4)

when opening recents in L15 (L14 beta 3 set as recents provider) it tells me to turn on Lawnchair debug accessibility service which is already on. when i go into accessibility settings, it says that this service is malfunctioning.

**Comment by s0m3th1ng-r4nd0m** [comment]
![Lawnchair (Debug) bug report Dec 5, 2024 11_59_13 PM.txt](https://github.com/user-attachments/files/18028290/Lawnchair.Debug.bug.report.Dec.5.2024.11_59_13.PM.txt)


another crash. i'm lazy to make a new issue for every crash so I'll just dump 'em here.

this one is reproducible by opening Playstore.

**Comment by s0m3th1ng-r4nd0m** [comment]
> ![Lawnchair (Debug) bug report Dec 5, 2024 11_59_13 PM.txt](https://github.com/user-attachments/files/18028290/Lawnchair.Debug.bug.report.Dec.5.2024.11_59_13.PM.txt)
> 
> 
> another crash. i'm lazy to make a new issue for every crash so I'll just dump 'em here.
> 
> this one is reproducible by opening play store or installing any apks from storage.


fixed in #5073

**Comment by guniens** [comment]
Hi!

Are you now able to set it as recents provider?

My Pixel 8 is on Android 15, Dec 2024 patch, latest Lawnchair's nightly and QuickSwitch but got error and cannot change recents provider.

Thanks in advance!

**Comment by s0m3th1ng-r4nd0m** [comment]
![Lawnchair (Debug) bug report Dec 11, 2024 2_07_47 PM.txt](https://github.com/user-attachments/files/18092511/Lawnchair.Debug.bug.report.Dec.11.2024.2_07_47.PM.txt)


this is the crash report with the latest nightly.

**Comment by guniens** [comment]
Sorry maybe I didn't explain.
I'm on latest nightly, Lawnchair works fine BUT when I set it as recents provider via QuickSwitch, QuickSwitch throws an error and no changes are made so I CANNOT set (as of now) Lawnchair as recents provider.

**Comment by s0m3th1ng-r4nd0m** [comment]
> Sorry maybe I didn't explain.
> I'm on latest nightly, Lawnchair works fine BUT when I set it as recents provider via QuickSwitch, QuickSwitch throws an error and no changes are made so I CANNOT set (as of now) Lawnchair as recents provider.

Oh, i can set it as my recents provider without any errors.
![Screenshot_20241211-161724.png](https://github.com/user-attachments/assets/fbd458c1-b6be-493e-9eb7-354192e636a1)

although it does not help in any way lmao.

**Comment by s0m3th1ng-r4nd0m** [comment]
![Lawnchair (Debug) bug report Dec 11, 2024 4_14_21 PM.txt](https://github.com/user-attachments/files/18094507/Lawnchair.Debug.bug.report.Dec.11.2024.4_14_21.PM.txt)

New crash report as of commit 55cce94125b5d615ae30c48792e0b52b4b5711a1 when set as the recents provider.

**Comment by guniens** [comment]
Hi again!

I got QuickSwitch to work [you probably aren't on latest Magisk version but I'm and I needed to do this](https://github.com/skittles9823/QuickSwitch/issues/73#issuecomment-2359895577).

Now I can set Lawnchair as recents provider and get a laggy, launch animation but costantly crashing (even rebooting) when opening recents like you.

@MrSluffy Can you please help?

**Comment by s0m3th1ng-r4nd0m** [comment]
> Hi again!
> 
> I got QuickSwitch to work [you probably aren't on latest Magisk version but I'm and I needed to do this](https://github.com/skittles9823/QuickSwitch/issues/73#issuecomment-2359895577).

Hey there!

I'm on Magisk 28.0 and i did not have to do this initially for my device but seeing it being a issue on my brothers device, i did it for myself too.

> Now I can set Lawnchair as recents provider and get a laggy, launch animation but costantly crashing (even rebooting) when opening recents like you.

You have to expect some lag from a development version but crashing can be fixed and I'm sure the devs are working on it.

**Comment by s0m3th1ng-r4nd0m** [comment]
> ![Lawnchair (Debug) bug report Dec 11, 2024 2_07_47 PM.txt](https://github.com/user-attachments/files/18092511/Lawnchair.Debug.bug.report.Dec.11.2024.2_07_47.PM.txt)
> 
> 
> this is the crash report with the latest nightly.

Fixed with commit 4feac9547f4e38205e3a21918e021569f65ab1b8

**Comment by MrSluffy** [comment]
any crashes? If no can we close this?

**Comment by guniens** [comment]
> any crashes? If no can we close this?

Hi

Not completely fixed:
- swipe back (app to homescreen) and then swipe up to open recents seems to work, animations are good too
- swipe up (app to homescreen) directly crashes lawnchair, also rebooted my device
- got some random crashes even now that I'm using chrome to type this

Thanks in advance btw!

**Comment by MrSluffy** [comment]
Please send crashlogs

**Comment by whoisabdi** [comment]
> Please send crashlogs

Here:

![Lawnchair (Debug) bug report Dec 12, 2024 10_01_36 AM.txt](https://github.com/user-attachments/files/18106784/Lawnchair.Debug.bug.report.Dec.12.2024.10_01_36.AM.txt)

![Lawnchair (Debug) bug report Dec 12, 2024 10_03_43 AM.txt](https://github.com/user-attachments/files/18106789/Lawnchair.Debug.bug.report.Dec.12.2024.10_03_43.AM.txt)

These were just 2 hours ago.

**Comment by ArniPL** [comment]
Latest nightly seems to work ok for me now. Recents work great, but only when using navigation buttons on Oxygen OS 15. Unfortunately when using navigation gestures, then swipe-up gesture to go to recents doesn't work at all. Just doesn't do a thing when swiping. I suppose Lawnchair doesn't register any swipe trigger. Can this be fixed? Thanks!

**Comment by CoelacanthusHex** [comment]
> Latest nightly seems to work ok for me now. Recents work great, but only when using navigation buttons on Oxygen OS 15. Unfortunately when using navigation gestures, then swipe-up gesture to go to recents doesn't work at all. Just doesn't do a thing when swiping. I suppose Lawnchair doesn't register any swipe trigger. Can this be fixed? Thanks!

I meet the same issue. The recents can only be called with a swipe-up gesture when I am on the home screen. If I'm in any other application, I can't swipe up to call out recents

**Comment by 0xAbdiiii** [comment]
> > Latest nightly seems to work ok for me now. Recents work great, but only when using navigation buttons on Oxygen OS 15. Unfortunately when using navigation gestures, then swipe-up gesture to go to recents doesn't work at all. Just doesn't do a thing when swiping. I suppose Lawnchair doesn't register any swipe trigger. Can this be fixed? Thanks!
> 
> I meet the same issue. The recents can only be called with a swipe-up gesture when I am on the home screen. If I'm in any other application, I can't swipe up to call out recents

My Lawnchair doesn't even startup when set as the recents provider 😁✌️

**Comment by MrSluffy** [comment]
> Latest nightly seems to work ok for me now. Recents work great, but only when using navigation buttons on Oxygen OS 15. Unfortunately when using navigation gestures, then swipe-up gesture to go to recents doesn't work at all. Just doesn't do a thing when swiping. I suppose Lawnchair doesn't register any swipe trigger. Can this be fixed? Thanks!

Send logs

**Comment by CoelacanthusHex** [comment]
> > Latest nightly seems to work ok for me now. Recents work great, but only when using navigation buttons on Oxygen OS 15. Unfortunately when using navigation gestures, then swipe-up gesture to go to recents doesn't work at all. Just doesn't do a thing when swiping. I suppose Lawnchair doesn't register any swipe trigger. Can this be fixed? Thanks!
> 
> Send logs

```
--------- beginning of crash
12-18 21:36:14.318 15653 15653 E AndroidRuntime: FATAL EXCEPTION: main
12-18 21:36:14.318 15653 15653 E AndroidRuntime: Process: app.lawnchair.debug, PID: 15653
12-18 21:36:14.318 15653 15653 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.android.launcher3.model.data.ItemInfo.getViewId()' on a null object reference
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.WorkspaceLayoutManager.addInScreen(WorkspaceLayoutManager.java:140)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.WorkspaceLayoutManager.addInScreenFromBind(WorkspaceLayoutManager.java:65)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.Launcher.bindInflatedItems(Launcher.java:2375)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.Launcher.bindInflatedItems(Launcher.java:2333)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$inflateAsyncAndBind$11(BaseLauncherBinder.java:429)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda4.execute(D8$$SyntheticClass:0)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.lambda$executeCallbacksTask$13(BaseLauncherBinder.java:451)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder.$r8$lambda$t7RE6I8t79xuZlzs9WoQFPVK6Y4(Unknown Source:0)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda10.run(D8$$SyntheticClass:0)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.util.RunnableList.executeAllAndClear(RunnableList.java:68)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.util.RunnableList.executeAllAndDestroy(RunnableList.java:56)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.util.ViewOnDrawExecutor.markCompleted(ViewOnDrawExecutor.java:92)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.ModelCallbacks$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.util.RunnableList.executeAllAndClear(RunnableList.java:68)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.util.RunnableList.executeAllAndDestroy(RunnableList.java:56)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.launcher3.model.BaseLauncherBinder$UnifiedWorkspaceBinder$$ExternalSyntheticLambda6.run(D8$$SyntheticClass:0)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:959)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:100)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at android.os.Looper.loopOnce(Looper.java:232)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:317)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:8592)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-18 21:36:14.318 15653 15653 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
12-18 21:36:14.441 15653 15653 I Process : Sending signal. PID: 15653 SIG: 9
```
So it's that the `child.getTag()` returns a null.

https://github.com/LawnchairLauncher/lawnchair/blob/683c17dcbf38c4290dfed64c10f429be67a51e33/src/com/android/launcher3/WorkspaceLayoutManager.java#L138-L40

And according to [the document](https://developer.android.com/reference/android/view/View#getTag()), `getTag()` returns null when the tag is not set.

**Comment by guniens** [comment]
Continues to happen in latest nighty

**Comment by 0xAbdiiii** [comment]
> Continues to happen in latest nighty 

can confirm. i stopped using nightly today because i can't resist the fluidity of Beta 3 set as the recents provider.

**Comment by imyxh** [comment]
I have the same issue as @imtheabdi, also on Android 12. (Complaining about createId and mNotFlags; see #5116 for logs.)

Downgrading to an older version of lawnchair (e.g. v12.0-alpha.5) seems to stop the crashing, but the recents button now just does nothing except the haptic feedback. v12.1.0-alpha.4 is the same, but additionally warns me that my system is too old for quickswitch to work.

Might be irrelevant, but I also noticed my stock launcher (LGHome.apk) also crashes when I tap the recents button; it throws

```
[ 12-23 23:58:54.508 13295:13295 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.lge.launcher3, PID: 13295
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4511)
	at com.android.quickstep.views.RecommandAppLayout.addItem(RecommandAppLayout.java:196)
	at com.android.quickstep.views.RecommandAppLayout.updateItems(RecommandAppLayout.java:167)
	at com.android.quickstep.views.RecentsView.reloadIfNeeded(RecentsView.java:1353)
	at com.android.quickstep.views.RecentsView.reloadIfNeeded(RecentsView.java:2909)
	at com.android.quickstep.views.RecentsView.updateTaskStackListenerState(RecentsView.java:1029)
	at com.android.quickstep.views.RecentsView.setOverviewStateEnabled(RecentsView.java:725)
	at com.android.quickstep.views.LauncherRecentsView.setOverviewStateEnabled(LauncherRecentsView.java:281)
	at com.android.quickstep.views.LauncherRecentsView.onStateTransitionStart(LauncherRecentsView.java:259)
	at com.android.quickstep.views.LauncherRecentsView.onStateTransitionStart(LauncherRecentsView.java:66)
	at com.android.launcher3.statemanager.StateManager.onStateTransitionStart(StateManager.java:368)
	at com.android.launcher3.statemanager.StateManager.goToState(StateManager.java:234)
	at com.android.launcher3.statemanager.StateManager.goToState(StateManager.java:150)
	at com.android.quickstep.LauncherActivityInterface.switchToRecentsIfVisible(LauncherActivityInterface.java:231)
	at com.android.quickstep.OverviewCommandHelper$RecentsActivityCommand.run(OverviewCommandHelper.java:224)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8005)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
```

when it tries to `.get(0)` on `LauncherAppsCompat.getInstance(this.mLauncher).getActivityList(itemToAdd, Process.myUserHandle())` which is apparently empty for some `addItem(String itemToAdd)`. (Stock quickstep not working is why I'm trying to see if I can find an alternative.)

**Comment by 0xAbdiiii** [comment]
> I have the same issue as @imtheabdi, also on Android 12. (Complaining about createId and mNotFlags; see #5116 for logs.)
> 
> Downgrading to an older version of lawnchair (e.g. v12.0-alpha.5) seems to stop the crashing, but the recents button now just does nothing except the haptic feedback. v12.1.0-alpha.4 is the same, but additionally warns me that my system is too old for quickswitch to work.
> 
> Might be irrelevant, but I also noticed my stock launcher (LGHome.apk) also crashes when I tap the recents button; it throws
> 
> ```
> [ 12-23 23:58:54.508 13295:13295 E/AndroidRuntime ]
> FATAL EXCEPTION: main
> Process: com.lge.launcher3, PID: 13295
> java.lang.IndexOutOfBoundsException: Index: 0
> 	at java.util.Collections$EmptyList.get(Collections.java:4511)
> 	at com.android.quickstep.views.RecommandAppLayout.addItem(RecommandAppLayout.java:196)
> 	at com.android.quickstep.views.RecommandAppLayout.updateItems(RecommandAppLayout.java:167)
> 	at com.android.quickstep.views.RecentsView.reloadIfNeeded(RecentsView.java:1353)
> 	at com.android.quickstep.views.RecentsView.reloadIfNeeded(RecentsView.java:2909)
> 	at com.android.quickstep.views.RecentsView.updateTaskStackListenerState(RecentsView.java:1029)
> 	at com.android.quickstep.views.RecentsView.setOverviewStateEnabled(RecentsView.java:725)
> 	at com.android.quickstep.views.LauncherRecentsView.setOverviewStateEnabled(LauncherRecentsView.java:281)
> 	at com.android.quickstep.views.LauncherRecentsView.onStateTransitionStart(LauncherRecentsView.java:259)
> 	at com.android.quickstep.views.LauncherRecentsView.onStateTransitionStart(LauncherRecentsView.java:66)
> 	at com.android.launcher3.statemanager.StateManager.onStateTransitionStart(StateManager.java:368)
> 	at com.android.launcher3.statemanager.StateManager.goToState(StateManager.java:234)
> 	at com.android.launcher3.statemanager.StateManager.goToState(StateManager.java:150)
> 	at com.android.quickstep.LauncherActivityInterface.switchToRecentsIfVisible(LauncherActivityInterface.java:231)
> 	at com.android.quickstep.OverviewCommandHelper$RecentsActivityCommand.run(OverviewCommandHelper.java:224)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:201)
> 	at android.os.Looper.loop(Looper.java:288)
> 	at android.app.ActivityThread.main(ActivityThread.java:8005)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
> ```
> 
> when it tries to `.get(0)` on `LauncherAppsCompat.getInstance(this.mLauncher).getActivityList(itemToAdd, Process.myUserHandle())` which is apparently empty for some `addItem(String itemToAdd)`. (Stock quickstep not working is why I'm trying to see if I can find an alternative.)


well the Lawnchair 14 Beta 3 works totally fine for me. I just have issues with Lawnchair 15 dev which i think will be fixed anyway before it's Beta 1 release. I just wanted to try and report crashes with Lawnchair 15 but it's unbearable without Quickswitch for me.

**Comment by yakat-web** [comment]
the update is that u can open recent app in home screen without problem but when u open recent app when u are in an app it crashes

**Comment by CraigHB** [comment]
I'm also having issues when I set Lawnchair as my recents provider.

OnePlus Nord N200
/e/os version e-2.8-a14 (Android 14)
Magisk 28.1.  
QuickSwitch 4.0.3
Lawnchair 14.0.0.Beta.3

After applying the file edit on util_functions.sh to get QuickSwitch working I'm able to assign Lawnchair as my recents provider.  

When the phone reboots I promptly get a text box stating that Lawnchair keeps crashing and prompts me to close it.  The recents provider reverts to the original.  Lawnchair otherwise works without flaw, just bombs as the recents provider.

**Comment by Zephyrus5929** [comment]
Has this issue been fixed ?

**Comment by imtheabdi** [comment]
> Has this issue been fixed ?

the issue is still open and development has halted for over a month now. all the developers are currently busy,

**Comment by whoisabdi** [comment]
Just tried setting the latest nightly build as the recents provider and Quickswitch fails. :)

**Comment by 0xAbdiiii** [comment]
the 15 beta 1 in fact does not work with Quickswitch.

![Lawnchair bug report Jul 15, 2025 12_15_55 PM.txt](https://github.com/user-attachments/files/21227769/Lawnchair.bug.report.Jul.15.2025.12_15_55.PM.txt)

**Comment by SeanDylan** [comment]
Any update? Also having the same problem
Lawnchair (Debug) bug report Jul 27, 2025 11:57:59 AM
version: 15.Dev.(#2443) (15000201)
commit: 025658c
build.brand: samsung
build.device: a20s
build.display: RP1A.200720.012.A207FXXS5CWF1
build.fingerprint: samsung/a20sxx/a20s:11/RP1A.200720.012/A207FXXS5CWF1:user/release-keys
build.hardware: qcom
build.id: RP1A.200720.012
build.manufacturer: samsung
build.model: SM-A207F
build.security.level: 2023-05-01
build.product: a20sxx
build.type: user
version.codename: REL
version.incremental: A207FXXS5CWF1
version.release: 11
version.sdk_int: 30
display.density_dpi: 275
isRecentsEnabled: true

error: Uncaught exception

java.lang.NoSuchMethodError: No static method getInstance()Landroid/app/ActivityTaskManager; in class Landroid/app/ActivityTaskManager; or its super classes (declaration of 'android.app.ActivityTaskManager' appears in /system/framework/framework.jar)
	at com.android.systemui.shared.system.ActivityManagerWrapper.<init>(ActivityManagerWrapper.java:78)
	at com.android.systemui.shared.system.ActivityManagerWrapper.<clinit>(ActivityManagerWrapper.java:69)
	at com.android.systemui.shared.system.ActivityManagerWrapper.getInstance(ActivityManagerWrapper.java:82)
	at com.android.quickstep.TouchInteractionService.onCreate(TouchInteractionService.java:581)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4661)
	at android.app.ActivityThread.access$1700(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2196)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by whoisabdi** [comment]
> Any update? Also having the same problem

I guess we'll have to wait until the Lawnchair 16 merge to see.

**Comment by SeanDylan** [comment]
> > Any update? Also having the same problem
> 
> i guess we'll have to wait until AOSP 16 merge to see.

That's going to take a very long time, ether we need someone to do a pr to fix this, or we have to wait for lawnchair 16

**Comment by SeanDylan** [comment]
Can anyone test if it's still broken? It's been a while

**Comment by whoisabdi** [comment]
Nothing has been fixed yet.
Here's something relevant: [Lawnchair 15 Roadmap](https://github.com/LawnchairLauncher/lawnchair/blob/15-dev/ROADMAP.md)

**Comment by SeanDylan** [comment]
> nothing has been fixed yet. check the end of this file: [roadmap](https://github.com/LawnchairLauncher/lawnchair/blob/15-dev/ROADMAP.md)

So i guess we quickswitch users will have to be sticking to lawnchair 14 for now, pretty sad we won't have a chance to even use lawnchair 15, possibly 16 if too many things would be broken or a breakthrough cannot be made for this, we'll have to wait and hope

**Comment by whoisabdi** [comment]
> > nothing has been fixed yet. check the end of this file: [roadmap](https://github.com/LawnchairLauncher/lawnchair/blob/15-dev/ROADMAP.md)
> 
> So i guess we quickswitch users will have to be sticking to lawnchair 14 for now, pretty sad we won't have a chance to even use lawnchair 15, possibly 16 if too many things would be broken or a breakthrough cannot be made for this, we'll have to wait and hope

I can't even use Lawnchair 14 on Lineage OS 22.2 as the recents provider so I'm just stuck on Lawnchair 15 Beta 1.

**Comment by SeanDylan** [comment]
> > > nothing has been fixed yet. check the end of this file: [roadmap](https://github.com/LawnchairLauncher/lawnchair/blob/15-dev/ROADMAP.md)
> > 
> > 
> > So i guess we quickswitch users will have to be sticking to lawnchair 14 for now, pretty sad we won't have a chance to even use lawnchair 15, possibly 16 if too many things would be broken or a breakthrough cannot be made for this, we'll have to wait and hope
> 
> I can't even use Lawnchair 14 on Lineage OS 22.2 as the recents provider so I'm just using Lawnchair 15 Beta 1.

That's weird that you could run it without startup crashes on android 15 but probably anything lower than that would crash

**Comment by SeanDylan** [comment]
For people who are experiencing the same issue it might be caused by the merge of lawnchair 15 which of course brings new bugs including this, for now please use this apk if you want a version close to lawnchair 15 https://www.apkmirror.com/apk/lawnchair/lawnchair-debug/lawnchair-debug-14-dev-1564-release/lawnchair-debug-14-dev-1564-android-apk-download/

**Comment by devlocalhost** [comment]
> For people who are experiencing the same issue it might be caused by the merge of lawnchair 15 which of course brings new bugs including this, for now please use this apk if you want a version close to lawnchair 15 https://www.apkmirror.com/apk/lawnchair/lawnchair-debug/lawnchair-debug-14-dev-1564-release/lawnchair-debug-14-dev-1564-android-apk-download/

I assume this does not work on modern android versions (like 15 or 16), right?

**Comment by SeanDylan** [comment]
> > For people who are experiencing the same issue it might be caused by the merge of lawnchair 15 which of course brings new bugs including this, for now please use this apk if you want a version close to lawnchair 15 https://www.apkmirror.com/apk/lawnchair/lawnchair-debug/lawnchair-debug-14-dev-1564-release/lawnchair-debug-14-dev-1564-android-apk-download/
> 
> I assume this does not work on modern android versions (like 15 or 16), right?

Since i think lawnchair 14 is based on android 14 i suppose it doesn't have support for those versions, because of this you should probably just use lawnchair 15 (only if you have a android 15 device) or if you're going to use android 16 wait for bubble tea to merge i'm not sure however so don't trust me

**Comment by itsMeRaj69** [comment]
> > > nothing has been fixed yet. check the end of this file: [roadmap](https://github.com/LawnchairLauncher/lawnchair/blob/15-dev/ROADMAP.md)
> > 
> > 
> > So i guess we quickswitch users will have to be sticking to lawnchair 14 for now, pretty sad we won't have a chance to even use lawnchair 15, possibly 16 if too many things would be broken or a breakthrough cannot be made for this, we'll have to wait and hope
> 
> I can't even use Lawnchair 14 on Lineage OS 22.2 as the recents provider so I'm just using Lawnchair 15 Beta 1.

@0xAbdiiii I'm on the same LineageOS and Lawnchair version. For me, setting Lawnchair as the recents provider (using Quickswitch) causes Trebuchet to crash. If Trebuchet is set as the default launcher while Lawnchair is the recents provider, Trebuchet crashes and shows a black screen. When I set both the default launcher and the recents provider to Lawnchair, accessing the recents tab crashes it.

**Comment by StarNumber12046** [comment]
Still broken on Android 16 and latest debug build from prereleases
