### ISSUE TITLE
[BUG] Widgets with settings pages don't work

### ISSUE THREAD

**Issue by pikuse** [Deletescape-Media/Lawnchair#5101]
### Describe the bug

Some widgets have seperate settings pages that are required for them to exist.
When placing a widget with settings, it either doesn't work or crashes Lawnchair.

### Steps to reproduce

> Steps to reproduce the behavior:
> 1. Open the widgets sheet
> 2. Place down any widgets that have a settings page
> 3. Widget settings page doesn't open
> 3.1 Lawnchair crashes, if forcefully opening widget settings page

### Expected behavior

The widget is placed down without any issues.

### Screenshots

https://github.com/user-attachments/assets/bbed07c0-a8ba-43c0-a1c4-efb0546d115d

### Device information

- Device: OnePlus Nord 3
- OS: OxygenOS 14.0.0.560
- App version: 15 Nightly (1811)

### Additional context

Doesn't happen on Lawnchair 14.

**Comment by MrSluffy** [comment]
Send crash logs

**Comment by pikuse** [comment]
[Lawnchair bug report 19.12.2024 17.01.04.txt](https://github.com/user-attachments/files/18199575/Lawnchair.bug.report.19.12.2024.17.01.04.txt)

**Comment by bappitybup** [comment]
appears to have been fixed as of nightly 29d3ad8

**Comment by charliefrance** [comment]
This is not fixed, can it be re opened please? The nightly build still has this issue on my Galaxy A35

**Comment by bappitybup** [comment]
> This is not fixed, can it be re opened please? The nightly build still has this issue on my Galaxy A35

oh, what's your android version?

**Comment by charliefrance** [comment]
> > This is not fixed, can it be re opened please? The nightly build still has this issue on my Galaxy A35
> 
> oh, what's your android version?

Android 14, I'm using the latest nightly build on my galaxy a35 so oneui 6.1

**Comment by charliefrance** [comment]
This is still not fixed in the latest nightly.

**Comment by MrSluffy** [comment]
https://streamable.com/15n8ud

**Comment by bappitybup** [comment]
> https://streamable.com/15n8ud

maybe somehow specific to OxygenOS 14 and OneUI 6.1? (unless the video is on either of these OS)
i can't test that myself right now

**Comment by charliefrance** [comment]
https://streamable.com/y8dagn
