### ISSUE TITLE
[BUG] Wallpaper pop-up carousel not showing 

### ISSUE THREAD

**Issue by guniens** [Deletescape-Media/Lawnchair#5148]
### Describe the bug

Wallpaper pop-up carousel isn't shown, latest nightly, allowed media permission, see screenshot.

### Steps to reproduce

1. Longpress on home screen
2. No wallpaper pop-up carousel, just the menu options like before

### Expected behavior

Wallpaper pop-up carousel should be shown.

### Screenshots

![Screenshot_20250109-093207](https://github.com/user-attachments/assets/576ae623-f17b-4d1a-84d5-2fe05d83bc22)

### Device information

- Device: Google Pixel 8
- OS: Android 15 (dec 2024 security patch)
- App version: Latest nightly (problem present since first nightly introduced wallpaper pop-up carousel)

**Comment by AndrewDallas** [comment]
Same here. 🙋

**Comment by MrSluffy** [comment]
Fixed use latest 80fbd9b2de5e472159d13cf57329ca04853ed90f

make sure you allowed storage permission

**Comment by guniens** [comment]
Not fixed, latest nightly and like a I said allowed media permission. I have no storage permission (?)

![Screenshot_20250109-101340](https://github.com/user-attachments/assets/d7683a4a-a5d4-43ec-bcad-5a564d24b572)
![Screenshot_20250109-101351](https://github.com/user-attachments/assets/aafef8ea-218c-4a8c-9751-2b90986ebf87)

**Comment by MrSluffy** [comment]
You need to set new wallpaper, that's the time it will store the wallpaper

check : [WallpaperService](https://github.com/LawnchairLauncher/lawnchair/blob/15-dev/lawnchair/src/app/lawnchair/wallpaper/service/WallpaperService.kt#L39)

![Screenshot_20250109-171809_Lawnchair](https://github.com/user-attachments/assets/e529a184-c390-419a-957e-700d560f5a40)

**Comment by guniens** [comment]
Thanks, works fine, my bad :)

**Comment by guniens** [comment]
However I noticed that changing wallpaper from the carousel sets lockscreen wallpaper to black/blank, should change it also for lockscreen or leave inalterated.

**Comment by MrSluffy** [comment]
if you set wallpaper from carousel it shouldn't affect the lock screen wallpaper 
https://streamable.com/p17nad

**Comment by guniens** [comment]
Not working for me like in your video.

If I chose a wallpaper from "wallpaper and style" settings I've it added to the carousel correctly and it changes correctly.

If I change it from the carousel directly it changes correctly for homescreen but lockscreen gets black (also tried rebooting system UI but no luck) and have to set it in "wallpaper and style" settings.

**Comment by MrSluffy** [comment]
I'll investigate that

**Comment by guniens** [comment]
Hi
Wallpaper carousel is gone completely with latest nightly, also tried changing wallpaper

**Comment by MrSluffy** [comment]
this is cause by the latest [commit](https://github.com/LawnchairLauncher/lawnchair/commit/4c241adb9b3a7f32909445dce63a27ab222b0e3b) but you can fix it by resetting the pop-up menu

Settings -> Home -> Edit Popup menus -> change any options then hit reset button

It will fix in upcoming nightly
