### ISSUE TITLE
[BUG] Lawnchair search widget only searches for the first word on web search

### ISSUE THREAD

**Issue by thealonealex** [Deletescape-Media/Lawnchair#5198]
### Describe the bug

I am using Arc Search for Android. When I search through the lawnchair search widget, only the first word of the search query is being searched for some reason? Doesn't matter which search engine. 

### Steps to reproduce

1. Set arc search as default browser
2. Use lawnchair app drawer search to search a more than 1 word query (in my case i tried "test test"
3. Click a web result or "Search with [search engine]
4. Only the first word is being searched (in my case, it only searched for "test"

### Expected behavior

I expected it to search normally, what can I say

### Screenshots

https://github.com/user-attachments/assets/ed86dc6e-789c-464b-988b-b7991da81d14

### Device information

- Device: OPPO A38
- OS: ColorOS 14
- App version: 14.Dev.(d7e3f32) [from google play store]

**Comment by MrSluffy** [comment]
Fixed use latest nightly https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly

**Comment by thealonealex** [comment]
> Fixed use latest nightly https://github.com/LawnchairLauncher/lawnchair/releases/tag/nightly

I just installed the latest nightly, and no, it is not fixed.

**Comment by MrSluffy** [comment]
https://github.com/user-attachments/assets/ada8fd36-2c88-4bec-9bae-d8c552fb0a27

**Comment by thealonealex** [comment]
> https://github.com/user-attachments/assets/ada8fd36-2c88-4bec-9bae-d8c552fb0a27

I specified this happens on a specific browser called Arc Search. It may be happening because you have spaces in the search query instead of putting `%20` between words? If this isn't the case, then it is an issue of the specific app and I'll let the devs know.

**Comment by thealonealex** [comment]
> > https://github.com/user-attachments/assets/ada8fd36-2c88-4bec-9bae-d8c552fb0a27
> 
> I specified this happens on a specific browser called Arc Search. It may be happening because you have spaces in the search query instead of putting `%20` between words? If this isn't the case, then it is an issue of the specific app and I'll let the devs know.
> 
> 

It appears like this is exactly the issue, since when I search "test%20test" it searches "test test". This is because links usually are not allowed to have spaces and that's why the `%20` stands for a space character. If you make sure that in every query the spaces are replaced for `%20`, it will work on all browsers.https://github.com/user-attachments/assets/de8c36e4-5512-4d22-9475-7491f6bdedc5
