### ISSUE TITLE
[BUG] Icon/folder in incorrect location when returning to the home screen

### ISSUE THREAD

**Issue by ZombieBear** [Deletescape-Media/Lawnchair#5497]
### Describe the bug

Device: Samsung Galaxy S21 ultra
Lawnchair 14 Beta 3
This issue started happening after the recent update to one UI 7.0
When opening an app and using it, upon returning to the home screen, the app icon or the folder containing it will be in the upper left corner of the home screen. It goes back to the correct location after any interaction so it's a minor visual glitch at worst, but still kind of odd. Screenshot attached

### Steps to reproduce

1. Open an app
2. Return to home scree
3. Make any input for the icon to return to the correct location

### Expected behavior

Icon or folder in which icon is contained remains in the original location

### Screenshots

![Image](https://github.com/user-attachments/assets/00fbe22a-1411-4eea-bdd8-12217e579307)

### Device information

Device: Samsung Galaxy S21 Ultra
OS: One UI 7.0 (Android 15)

### App version

14 Beta 3

**Comment by skipcoon** [comment]
Also happening on -

Device: OnePlus Nord N20
OS: Android v12

**Comment by 0xAbdiiii** [comment]
iirc, it got fixed in the nightly build a few months ago. the only way to fix it in beta 3 (like i am doing) is to use Lawnchair as recents provider (requires root.)

**Comment by ghost** [comment]
I'm still having this issue on the latest version of lawnchair on my z fold 3

**Comment by anpandiyaraj** [comment]
First fix annoying basic bug before giving future support. Dev team is considering this issue or not.

**Comment by 0xAbdiiii** [comment]
> First fix annoying basic bug before giving future support. Dev team is considering this issue or not. 

you're being rude, buddy. the dev team is doing their best and this issue is probably related to recents provider issue because it disappears when Lawnchair is set as the recents provider. one of the devs tried fixing it a year ago but it didn't work that great so.. be grateful for what you have.

**Comment by ghost** [comment]
cmon guys, not the place or time to start poking at each other

**Comment by SuperDragonXD** [comment]
Closing as a duplicate of #5651
