### ISSUE TITLE
Broke Animation

### ISSUE THREAD

**Issue by MoHamed-B-M** [Deletescape-Media/Lawnchair#5615]
### Describe the bug

When launching or closing apps from the home screen, the animation appears glitchy, stuttery, or broken, instead of the smooth transition expected in Lawnchair. This may manifest as:

App icons jumping abruptly instead of smoothly scaling.

### Steps to reproduce

1. Install the latest Lawnchair version.

2. Tap on any app icon from the home screen.

3. Observe the transition animation.

4. Return to home and observe the closing animation.

### Expected behavior

App open/close transitions should mirror stock Android's fluid motion, with smooth scaling, opacity changes, and responsiveness.

### Screenshots

https://github.com/user-attachments/assets/b0439e83-0a5b-46ba-aa4a-97cacdddefea

### Device information

Device: Oppo Reno 3

Android Version: 12

Lawnchair Version: 15 Beta 1

ROM: ColorOS (12)

### App version

15 beta 1

**Comment by ThatGreenBlur** [comment]
turn off app closing animation in Home Screen as a remedy for now

**Comment by DhyanM025** [comment]
Same here, on Pixel 6a Android 16. Though it's not as bad, the app icon glitches for a second after the app closing animation.

**Comment by ozumado** [comment]
On NothingOS the animation doesn’t even work, there is always a default animation (app scrolls up/down)

**Comment by TechD123** [comment]
Reproducible on FP4, Android 15

In addition to the glitch in the app minimization the wobble of the app icon is broken, too.

**Comment by ThatGreenBlur** [comment]
> Reproducible on FP4, Android 15
> 
> In addition to the glitch in the app minimization the wobble of the app icon is broken, too.

app wobble for me got fixed by deselecting and selecting lawnchair as main launcher in my experience lol

**Comment by TechD123** [comment]
> app wobble for me got fixed by deselecting and selecting lawnchair as main launcher in my experience lol

The app wobble had disappeared for me in the meantime (while app minimization was still buggy); reselecting Lawnchair made the app wobble return, somehow. So there _is_ a correlation here.

**Comment by ThatGreenBlur** [comment]
> > app wobble for me got fixed by deselecting and selecting lawnchair as main launcher in my experience lol
> 
> The app wobble had disappeared for me in the meantime (while app minimization was still buggy); reselecting Lawnchair made the app wobble return, somehow. So there _is_ a correlation here.

i recommend doing that trick and selecting app closing animation in home screen settings as none for it to look normal enough
