### ISSUE TITLE
[BUG] registerBackDispatcher NSDEF crash on Android 13

### ISSUE THREAD

**Issue by TolerantLescnq7** [Deletescape-Media/Lawnchair#6028]
### Describe the bug

The latest 16-dev crashes on a Samsung A51 running One UI 5.1. I don't know if this is the case with other devices.

### Steps to reproduce

1. Open the app from the 16-dev branch
2. See the crash

### Expected behavior

I expect it to atleast open.

### Screenshots

N/A

### Device information

- Device: Samsung A51
- OS: One UI 5.1, Android 13

### App version

Latest app from the 16-dev branch

### Additional context

[Lawnchair bug report Oct 27, 2025 07_08_57.txt](https://github.com/user-attachments/files/23154062/Lawnchair.bug.report.Oct.27.2025.07_08_57.txt)

**Comment by validcube** [comment]
Fixed, try downloading the latest build of `16-dev`

**Comment by TolerantLescnq7** [comment]
> Fixed, try downloading the latest build of `16-dev`

I tried the newest APK but it still crashes.

https://katb.in/nakavupagij

**Comment by validcube** [comment]
Try again @ https://github.com/LawnchairLauncher/lawnchair/actions/runs/19162017010

**Comment by TolLescnq7** [comment]
> Try again @ https://github.com/LawnchairLauncher/lawnchair/actions/runs/19162017010

https://katb.in/bicadihekak
Still the same... I can open the Home Settings using activities if that helps?

**Comment by validcube** [comment]
> > Try again @ https://github.com/LawnchairLauncher/lawnchair/actions/runs/19162017010
> 
> https://katb.in/bicadihekak Still the same... I can open the Home Settings using activities if that helps?

Don't worry about that, keep trying the APK again, I think this is the last fix you'll need now.

https://github.com/LawnchairLauncher/lawnchair/actions/runs/19204677239/job/54898084493

**Comment by TolerantLescnq7** [comment]
> > > Try again @ https://github.com/LawnchairLauncher/lawnchair/actions/runs/19162017010
> > 
> > 
> > https://katb.in/bicadihekak Still the same... I can open the Home Settings using activities if that helps?
> 
> Don't worry about that, keep trying the APK again, I think this is the last fix you'll need now.
> 
> https://github.com/LawnchairLauncher/lawnchair/actions/runs/19204677239/job/54898084493

It works! Lawnchair's homescreen opens normally.
