### ISSUE TITLE
Weird font in shortcuts

### ISSUE THREAD

**Issue by RWOne** [Deletescape-Media/Lawnchair#81]
Asking because I haven't a real Pixel, but the bolded text in the shortcuts, needed? 

Don't get me wrong, perhaps I'm used to non bolded, shadowed text on my device.

**Comment by deletescape** [comment]
This is actually a bug I noticed myself, forgot to fix it before the release, should be fixed pretty soon

**Comment by edisso10018** [comment]
This seems to be not yet fixed. The shadow is still there. At least on Android 7.1.1.

**Comment by paphonbth** [comment]
Seems to happen with icon actions (Edit, Widgets, App info) but the app shortcuts are fixed.
