### ISSUE TITLE
Unresponsive top row

### ISSUE THREAD

**Issue by jise** [Deletescape-Media/Lawnchair#980]
## Description
Any icon or widget placed on the top row could have been unresponsive after a while to the touch.

## Expected Behavior
Any icon or widget placed everywhere on the screen should have been responsive to the touch the same way regardless of its placement on the screen.

## Actual Behavior
Any icon or widget placed on the top row could have been unresponsive after a while to the touch in such a way that icon or widget react only to the touch targeted to the low third part of the object.

## Steps to Reproduce
1. Place Chrome icon on the top row of your screen, for the testing purpose put it to the new blank screen. I choose Chrome icon as a helper just because it is visually divided into thirds, but you can use any icon of course.
2. After that restart Lawnchair launcher from the Debug menu. (This step is important to quickly trigger the bug with the next two steps, I hope that it will be the hint for the developer why. Without this step, the error appearing will take much more time and it will seems random.)
3. Long touch the top third (or middle third) of the Chrome icon to display Oreo shortcuts.
4. Long touch the top third (or middle third) of the Chrome icon once more. Oreo shortcuts will not appear now nor on any consecutive long touch the top third (or middle third) of the Chrome icon.
5. You could continue from the step number 2 infinitely.

or as a workaround

Long touch the bottom third of the Chrome icon to display Oreo shortcuts every time.

## Environment
Tested on Nexus 5X 8.1.0 and Xiaomi Mi A1 7.1.2 with Lawnchair version 1.1.0.1667.
I even have a colleague at work who confirm this behaviour, but he cannot post here.

## Something similar has been reported before
Yes, in issues #339 and #525, but these old issues stayed unnoticed because vague descriptions.

**Comment by jise** [comment]
This bug is still present in Lawnchair version 1.1.0.1730.

**Comment by byytelope** [comment]
Now I can experience it too.

**Comment by jise** [comment]
Please don't forget click to smile icon on the top right of the first post and select +1 to confirm this issue.
I hope that we get the attention of the developers now as confirmed.
Thank you very much.

**Comment by divadsn** [comment]
Rule no. 1 of FOSS: Don't ask for ETA, be patient.

So please, don't bother us with raising attention, we already noticed it, but we don't have time...

**Comment by jise** [comment]
I am sorry for this. I had a false feeling that no one noticed this issue when there were no reactions.
Then it was hard to reproduce the issue by other user...
Now I know that you know 👼 
Thank you!

**Comment by minhdangoz** [comment]
This problem is caused by DropTargetBar is on the top of shortcut, so we can not click to shortcut by easily way, if touch to botton of icon then we can open it.
I already fixed this problem by myself

**Comment by jise** [comment]
This bug is still present in Lawnchair version 1.1.0.1834.
Xiaomi Mi A1 8.0.0.

**Comment by divadsn** [comment]
@jise And now what?

**Comment by jise** [comment]
What?

I have a feeling that we don't understand each other standpoint. Lawnchair team asked users for reporting bugs: "Check out Lawnchair's GitHub. Help out by fixing bugs, flagging issues, or even by just downloading and testing!". So I am just reporting bugs here, because I really like Lawnchair and want to help you.

Or did you mean by your reply when only icons on the top row of every your screen are affected by this bug that it is normal or only small issue? I never encounter such a behaviour in any other launcher.

To be honest I even didn't understand previous comment "This problem is caused by DropTargetBar is on the top of shortcut, so we can not click to shortcut by easily way, if touch to botton of icon then we can open it.". Is this just an confirmation of my workaround I already mentioned?

This issue hasn't any assignees, any labels, etc - so it looks like unnoticed. The same was/is true for two old issues I linked. I already explained my standpoint in comment on 8 Dec 2017.

I just actualized this bug report today for the new Lawnchair version installed and the new Android version installed.

**Comment by divadsn** [comment]
@jise Just because we don't reply doesn't mean we don't have that bug on our todo listm

**Comment by jise** [comment]
Ok, but how could reporting and participated users know that devs already have any particular reported issue on their todo list? By telepathy? That silence is even reason for many duplicate issues.

Using this would be better way:
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone

Because if I did know from here that this is known bug I didn't waste my and your time with another issue #980. I precisely checked repository of issues prior publishing it and only noticed the same reports in issues #339 and #525, but these old issues stayed unnoticed, unconfirmed, I mean formally and publicly here. Another problem was that it was very hard to reproduce this issue by other users (no one from my friends which are using Lawnchair know about this issue when I asked them) so I tried to document it as best as possible.

And the reaction? It wasn't Thank you or Confirmed or Assigned, but "don't bother us with raising attention, we already noticed it, but we don't have time". Even a few seconds for sticking the appropriate Label?

**Comment by divadsn** [comment]
@jise We have labels and some of those issues have also links to Trello. I'm sorry, but I am currently not able to tell any more details than the fact that we are getting back doing updates and fixes, as we moved all our stuff to the new server which took a lot time for me.

**Comment by divadsn** [comment]
@divadsn Also, we don't close issues if we think that this should be added or fixed, so open issues are ALWAYS on our heads-up, no matter what we did so far. If we find out after a long time that the issue can't be solved then we close the issue and thank everyone for trying out.

**Comment by jise** [comment]
There is no need to apologize, I highly appreciate your work, but please do not make the error reporting a bigger problem than it is. So your last reply should be carved on each page here :)

**Comment by galexander1** [comment]
I just experienced this problem (version 1.2.0.1884).  I think DropTargetBar is a likely culprit (per @minhdangoz) because long-holding then dragging an icon causes the problem to go away.

Unfortunately I have not yet figured out how to make the problem begin.

**Comment by schokotets** [comment]
Can confirm the issue, still. Version 1.2.0.1884, Samsung Galaxy S7.
Before, I've only experienced a related issue with borderless full-screen widgets and their top row, which became unresponsive at times. I can't reproduce it yet. Will update if I should.
